entries:
  - search_title: "黑客帝国"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/黑客帝国"

  - search_title: "火星救援"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/火星救援"

  - search_title: "健听女孩"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/健听女孩"

  - search_title: "战争与和平"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/战争与和平"

  - search_title: "神迹"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/神迹"

  - search_title: "费城故事"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/费城故事"

  - search_title: "肖申克的救赎"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/肖申克的救赎"

  - search_title: "风雨哈佛路"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/风雨哈佛路"

  - search_title: "汉密尔顿"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/汉密尔顿"

  - search_title: "最后的决斗"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/最后的决斗"

  - search_title: "脸庞村庄"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/脸庞，村庄"

  - search_title: "菊次郎的夏天"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/菊次郎的夏天"

  - search_title: "码头风云"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/码头风云_On the Waterfront"

  - search_title: "蓝白红三部曲之蓝"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/蓝白红-三部曲"

  - search_title: "鸟人"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/鸟人_Birdman"

  - search_title: "地狱尖兵"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/地狱尖兵"

  - search_title: "英国病人"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/英国病人"

  - search_title: "芝加哥七君子审判"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/芝加哥七君子审判"

  - search_title: "巴比伦"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/巴比伦"

  - search_title: "西部往事"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/西部往事"
