entries:
  - search_title: "少年斯派维的奇异旅行"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/少年斯派维的奇异旅行_The Young and Prodigious T.S. Spivet"

  - search_title: "傲慢与偏见"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/傲慢与偏见"

  - search_title: "自闭历程"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/自闭历程"

  - search_title: "无主之作"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/无主之作"

  - search_title: "爆裂鼓手"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/爆裂鼓手"

  - search_title: "用心棒"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/用心棒_Yojimbo"

  - search_title: "被解救的姜戈"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/被解救的姜戈"

  - search_title: "搏击俱乐部"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/搏击俱乐部"

  - search_title: "风月俏佳人"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/风月俏佳人"

  - search_title: "冰川时代"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/冰川时代_Ice Age"
