entries:
  - search_title: "控方证人"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/控方证人"

  - search_title: "十二怒汉"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/十二怒汉"

  - search_title: "教父"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/教父系列"

  - search_title: "生之欲"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/生之欲_Ikiru"

  - search_title: "海上钢琴师"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/海上钢琴师"

  - search_title: "海蒂和爷爷"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/海蒂和爷爷"

  - search_title: "生活多美好"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/Its a Wonderful Life 1946_Its a Wonderful Life"

  - search_title: "鲁邦三世"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/宫崎骏系列"

  - search_title: "黑客帝国三部曲"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/The Complete Matrix Trilogy Bluray 720p DTS 2Audio x264-CHD_The Complete Matrix Trilogy Bluray 720p DTS 2Audio x264-CHD"

  - search_title: "天地玄黄"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/天地玄黄"

  - search_title: "指环王1护戒使者"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/指环王与霍比特人系列6部曲"

  - search_title: "从海底出击"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/从海底出击"

  - search_title: "哈利波特"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/哈利波特 1-9合集+邓布利多"

  - search_title: "两杆大烟枪"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/两杆大烟枪_Lock Stock and Two Smoking Barrels"

  - search_title: "7号房的礼物"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/7号房的礼物"

  - search_title: "致命ID"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/致命ID_Identity"

  - search_title: "爱在午夜降临前"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/爱在午夜降临前_Before Midnight"

  - search_title: "爱在日落黄昏时"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/爱在日落黄昏时_Before Sunset"

  - search_title: "终结者2"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/终结者2"

  - search_title: "莫里斯"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/莫里斯_Maurice"

  - search_title: "爱尔兰人"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/爱尔兰人"

  - search_title: "回到未来"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/回到未来_Back to the Future"

  - search_title: "断背山"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/断背山_Brokeback Mountain"

  - search_title: "哭泣的草原"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/哭泣的草原"

  - search_title: "骗中骗"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/骗中骗_The Sting"

  - search_title: "弗里达"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/弗里达"

  - search_title: "无耻混蛋"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/无耻混蛋"

  - search_title: "坠落的审判"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/坠落的审判"

  - search_title: "莫扎特传"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/莫扎特传"

  - search_title: "内布拉斯加"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/内布拉斯加"
