entries:
  - search_title: "回到未来3"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/回到未来3_Back to the Future Part III"

  - search_title: "诺丁山"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/诺丁山_Notting Hill"

  - search_title: "重庆森林"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/重庆森林"

  - search_title: "落水狗"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/落水狗"

  - search_title: "教宗的承继"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/教宗的承继"

  - search_title: "K星异客"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/K星异客"

  - search_title: "曾经"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/曾经_Once"

  - search_title: "银翼杀手2049"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/银翼杀手"

  - search_title: "终结者"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/终结者系列"

  - search_title: "训练日"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/训练日_Training Day"

  - search_title: "倒数时刻"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/倒数时刻"

  - search_title: "波斯语课"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/波斯语课"

  - search_title: "华尔街之狼"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/华尔街之狼"

  - search_title: "万湖会议"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/万湖会议"

  - search_title: "每分钟120击"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/每分钟120击_120 battements par minute"
