entries:
  - search_title: "泰坦尼克号"
    kind_hint: movie
    nas_library_path: "meta:douban:1292722"

  - search_title: "阿甘正传"
    kind_hint: movie
    nas_library_path: "meta:douban:1292720"

  - search_title: "楚门的世界"
    kind_hint: movie
    nas_library_path: "meta:douban:1292064"

  - search_title: "星际穿越"
    kind_hint: movie
    nas_library_path: "meta:douban:1889243"

  - search_title: "这个杀手不太冷"
    kind_hint: movie
    nas_library_path: "meta:douban:1295644"

  - search_title: "盗梦空间"
    kind_hint: movie
    nas_library_path: "meta:douban:3541415"

  - search_title: "忠犬八公的故事"
    kind_hint: movie
    nas_library_path: "meta:douban:3011091"

  - search_title: "活着"
    kind_hint: movie
    nas_library_path: "meta:douban:1292365"

  - search_title: "触不可及"
    kind_hint: movie
    nas_library_path: "meta:douban:6786002"

  - search_title: "无间道"
    kind_hint: movie
    nas_library_path: "meta:douban:1307914"

  - search_title: "教父2"
    kind_hint: movie
    nas_library_path: "meta:douban:1299131"

  - search_title: "钢琴家"
    kind_hint: movie
    nas_library_path: "meta:douban:1296736"

  - search_title: "素媛"
    kind_hint: movie
    nas_library_path: "meta:douban:21937452"

  - search_title: "七武士"
    kind_hint: movie
    nas_library_path: "meta:douban:1295399"

  - search_title: "城市之光"
    kind_hint: movie
    nas_library_path: "meta:douban:1293908"

  - search_title: "黄金三镖客"
    kind_hint: movie
    nas_library_path: "meta:douban:1401118"

  - search_title: "切腹"
    kind_hint: movie
    nas_library_path: "meta:douban:1304920"

  - search_title: "地球之盐"
    kind_hint: movie
    nas_library_path: "meta:douban:10741871"

  - search_title: "控方证人"
    kind_hint: movie
    nas_library_path: "meta:douban:1296141"

  - search_title: "十二怒汉 1957"
    kind_hint: movie
    nas_library_path: "meta:douban:1293182"

  - search_title: "剧院魅影25周年"
    kind_hint: movie
    nas_library_path: "meta:douban:24751811"

  - search_title: "悲惨世界25周年"
    kind_hint: movie
    nas_library_path: "meta:douban:24882562"

  - search_title: "大闹天宫 1961"
    kind_hint: movie
    nas_library_path: "meta:douban:1418019"

  - search_title: "放牛班的春天"
    kind_hint: movie
    nas_library_path: "meta:douban:1291549"

  - search_title: "高山下的花环"
    kind_hint: movie
    nas_library_path: "meta:douban:1422283"

  - search_title: "回忆积木小屋"
    kind_hint: movie
    nas_library_path: "meta:douban:3560787"

  - search_title: "海蒂和爷爷"
    kind_hint: movie
    nas_library_path: "meta:douban:25958717"

  - search_title: "万物与虚无"
    kind_hint: movie
    nas_library_path: "meta:douban:6872214"

  - search_title: "莫扎特音乐剧"
    kind_hint: movie
    nas_library_path: "meta:douban:27666513"

  - search_title: "银魂"
    kind_hint: tv
    nas_library_path: "meta:douban:2057171"
