entries:
  - search_title: "8英里"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/8英里"

  - search_title: "沉静如海"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/沉静如海_Le silence de la mer"

  - search_title: "黑洞频率"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/黑洞频率"

  - search_title: "犬之力"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/犬之力"

  - search_title: "辩护人"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/辩护人"

  - search_title: "珍珠港"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/珍珠港"

  - search_title: "超时空接触"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/超时空接触_Contact"

  - search_title: "赤裸特工"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/赤裸特工"

  - search_title: "回到未来2"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/回到未来2_Back to the Future Part II"

  - search_title: "大而不倒"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/Too Big To Fail 2011_Too Big To Fail"

  - search_title: "真实的谎言"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/真实的谎言"

  - search_title: "猎鹿人"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/猎鹿人_The Deer Hunter"

  - search_title: "碟中谍"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/碟中谍1-6"

  - search_title: "卡桑德拉大桥"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/卡桑德拉大桥"

  - search_title: "鹬"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/Piper 2016_Piper"

  - search_title: "一个叫欧维的男人决定去死"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/一个叫欧维的男人决定去死"

  - search_title: "华尔街"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/华尔街"

  - search_title: "灵魂歌王"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/灵魂歌王"

  - search_title: "星球大战"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/星球大战 1-11部"

  - search_title: "海豚湾"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/海豚湾"
