entries:
  - search_title: "南极大冒险"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/南极大冒险_Eight Below"

  - search_title: "阿甘正传"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/阿甘正传"

  - search_title: "星际迷航"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/星际迷航1-13"

  - search_title: "走出非洲"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/走出非洲_Out of Africa"

  - search_title: "紫日"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/紫日"

  - search_title: "了不起的盖茨比"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/了不起的盖茨比"

  - search_title: "她比烟花寂寞"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/她比烟花寂寞"

  - search_title: "最后的城堡"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/最后的城堡"

  - search_title: "水"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/Water 2005_Water"

  - search_title: "少年派的奇幻漂流"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/少年派的奇幻漂流_Life of Pi"

  - search_title: "放牛班的春天"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/放牛班的春天"

  - search_title: "熔炉"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/熔炉"

  - search_title: "小美人鱼"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/小美人鱼"

  - search_title: "相约星期二"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/相约星期二"

  - search_title: "寄生虫"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/寄生虫"

  - search_title: "午宴之歌"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/The Song of Lunch (2010)_The Song of Lunch"

  - search_title: "轮回"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/轮回"

  - search_title: "落水狗"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/落水狗"

  - search_title: "国家地理心事谁人知"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/国家地理 心事谁人知 生命之泵 六四_National Geographic The Secret Heart Pumped"

  - search_title: "重庆森林"
    kind_hint: movie
    nas_library_path: "/volume1/homes/影视资源库/重庆森林"
